# Neural Networks  - Part I

Author: Ethan Robert A. Casin

---

## Introduction

One of the main inspirations of modern deep learning is actually the human brain. Back then, scientists were interested on how the brain is able to process information and be able to create abstract thought and consciousness. More than that, it was more interesting to learn that these emergent properties were brought about by relatively simple cells called neurons.

These neurons behave rather simply: if prompted, it will either fire or not.

Moreover, neurons have the capacity to rewire and even create new pathways. There's this famous line on how neurons connect: "neurons that fire together, wire together". This is known as Hebb's rule. But what does this have to do with neural networks?

<figure style="text-align:center">
    <img src="figures/neurons.png" width="70%">
    <figcaption style="text-align:left">Figure 1. Illustration of a biological neuron (left) and an artificial neuron (right). This figure illustrates how the artificial neuron is inspired by biological ones, where the dendrites correspond to the inputs of a neuron, while the output is analogous to the axon. It is interesting to see that the biological neuron is assumed to be a function that maps the inputs to an output.</figcaption>
</figure>


As the name suggests, artificial neural networks (ANNs) were inspired by biological neurons. If we look at the image above, biological neurons have dendrites, which connect with other neurons. It then gets processed in the nucleus. And then the corresponding signal output is sent to through the axon and to the axon terminals. There the final decision whether it will fire or not will occur at the synapse -- small gaps in between two neurons that acts as a communication point.

In much the same manner, we can take inspiration from these neurons to create an artificial neuron using mathematics and enabled by compute.

Luckily in the 1950s we already know a mathematical formula that can mimic the act of neurons firing. It's called a step function, which, if a value meets a certain threshold, would yield a value of 1 (fire) or 0 (don't fire). The most commonly used step function called Heaviside Step Function


<figure style="text-align:center">
    <img src="https://mathworld.wolfram.com/images/eps-svg/HeavisideStepFunction_900.svg" width="70%">
    <figcaption style="text-align:left">Figure 2. Illustration of a Heaviside Function retried from <a href="https://mathworld.wolfram.com/images/eps-svg/HeavisideStepFunction_900.svg">here.</a></figcaption>
</figure>


---

**Question**

Do ANNs really function the same way as biological neural networks? Are they really that similar?

---

## Quick History: The Perceptron

In the 1950s, the US navy was able to build its first workable ANN.

Pioneered by Frank Rosenblatt, he was able to create the perceptron. At the time, it was good enough to classify male or female based on input images. This perceptron was made in order to do image recognition tasks. Watch the video [here](https://www.youtube.com/embed/cNxadbrN_aI) to see how it worked.

We'll see later why after the development of the perceptron, lead to the first winter of AI. To gain a better understanding of how the perceptron worked, refer to the image below.

<figure style="text-align:center">
    <img src="figures/perceptron.png" width="25%">
    <figcaption style="text-align:left">Figure 3. General architecture of a perceptron.</a></figcaption>
</figure>

If we take a look at the architecture given, the perceptron doesn't actually look like any neuron we know. Nor does it resemble modern ANNs now. Which is exactly the point. Because the perceptron was actually modeled after logic gates, but what makes this interesting is the fact that you don't need to explicity code out how the perceptron should make its decisions. Rather it learns by example.


### Under the microscope

Let's now try to understand why we got stuck in the first place.

Since we saw that the Perceptron was mostly classification, let's level with that for a bit. Fundamentally, we can actually generalize bitwise calculations using three operations: $\text{OR}$, $\text{AND}$, and $\text{XOR}$.



---

**Question**

When is the output 1 for $\text{OR}$, $\text{AND}$, and $\text{XOR}$?

---

Let's try to predict each $\Psi$ value using a perceptron. Below is the truth table for a sample dataset and their corresponding outputs for each operation.

|$x_1$ | $x_2$ | $\Psi_{\text{AND}}$| $\Psi_{\text{OR}}$| $\Psi_{\text{XOR}}$|
| ---  | ----  |  -----| --- | --- |
| -1   | -1    | 0| 0 | 0|
|-1    | 1     | 0| 1| 1|
|1     | -1    | 0| 1| 1|
|1     | 1     |1 | 1| 0 |

Luckily, scikit-learn already has a Perceptron model in their library.

---

**Activity**

When does the Perceptron fail? Why?

If there was 1 change you could do to the model, what would it be?

---

In [2]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score

In [3]:
X = np.array(
    [
        [-1, -1],
        [-1, 1],
        [1, -1],
        [1, 1]
    ]
)

y = [0, 1, 1, 0] # Change the targets based on the chosen Psi column

perceptron_model = Perceptron(random_state=42).fit(X, y)
y_preds = perceptron_model.predict(X)

accuracy = accuracy_score(y, y_preds)
print(f"{y_preds=}")
print(f"Accuracy: {accuracy * 100:.2f}%")

y_preds=array([0, 0, 0, 0])
Accuracy: 50.00%


If you noticed, the perceptron tends to fail in predicting the $\text{XOR}$ operation. If you actually plot out the truth table for this operation, you'd notice that the perceptron is limited to predicting only linearly separable systems. It fails for non-linear cases.

This is infamously known as the $\text{XOR}$ problem, which sparked the very first AI winter. This lasted about 30 years, until 3 people decided to do something about it.

## Backpropagation: This changes everything!

The introduction of the Perceptron created the very first hype around AI around the late 1950s, but quickly met its demise due to its limitations.

Rumelhart (lead), Hinton, and Williams in their paper [Learning representations by backpropagating errors](https://www.nature.com/articles/323533a0) back in 1986. The idea is simple: make the activation function continuous and backpropagate the errors from the front to the back. 

*Note: Of course this is an oversimplification of their work, but I want to illustrate that even simple changes and ideas could spark revolutionary changes. **Stay creative.***


A family of continuous functions that would reliably approximate the step function are sigmoid functions.

<div class="row" align="center">
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Logistic-curve.svg/500px-Logistic-curve.svg.png" width="30%"></img>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Gjl-t%28x%29.svg/2880px-Gjl-t%28x%29.svg.png" width="40%"></img><br>
<caption>Figure 4. The Sigmoid function (left) and the Sigmoid function family (right).</caption>
</div>

There are many members of the sigmoid family, but the they generally look like this:

\begin{equation*}
f(x) = \frac{A}{1 + e^{-k(x-x_o)}},
\end{equation*}

where $A$ is the maximum value, $x_o$ is the location of the midpoint, and $k$ is the steepness of the curve. Essentially, sigmoids are defined by two horizontal asymptotes. This is the main reason why they are often used for learning curves, activations functions, and other growth models that exhibit an approximately exponential increase that saturates at a certain point.

---
**Activity**

Suppose that our sigmoid is defined as

$$f(x) = \frac{1}{1 + e^{-kx}}$$

Then its first derivative $f'(x)$ can be defined as

$$f'(x) = kf(x)(1 - f(x))$$

Prove that this is true.

---

### Single output neural network...from scratch

Let's now create a neural network from scratch. Let's follow the architecture below and we'll learn a few more concepts along the way.

<figure style="text-align:center">
<img src="figures/basic-network.png" width="40%">
</figure>

Let's first try to understand how this neural network works mathematically.

**Step 1. Forward Propagation**
The functional mapping from inputs $(x_1, x_2)$ to the output $\Psi_{NN}$ is given by

$$\Psi_{NN} = g(x_1, x_2) = g(w_1f_1(x_1), w_2f_2(x_2)),$$

where $w_1$ and $w_2$ are the learnable weights, and $f_1, f_2$, and $g$ are the activation functions. 

**Step 2. Define the error**

If you want your system a mapping from $\Psi_{NN}$ to $\Psi_{\text{actual}}$, then we need a way to let it know when it's getting things wrong. In this case, we need to define an error function $E$. 

$$E = \frac{1}{2}(\Psi_{NN} - \Psi_{\text{actual}})^2$$

Having a defined error function allows us to update $w_1$ and $w_2$. Note that the $1/2$ is only placed for mathematical convenience.

**Step 3. Implement Gradient Descent**

We then need an update rule, so that for each iteration our weights get updated. This is done using gradient descent.

$$w_1^{t + 1} = w_1^t - \gamma\frac{\partial E}{\partial w_1^t}$$
$$w_2^{t + 1} = w_2^t - \gamma\frac{\partial E}{\partial w_2^t}$$

For this derivation, let's assume that we will be using the sigmoid we defined earlier for all activation functions. 

$$w_1^{t + 1} = w_1^t - \gamma(\Psi_{NN} - \Psi_{\text{actual}})g'(x_1, x_2)f_1(x_1)$$
$$w_2^{t + 1} = w_2^t - \gamma(\Psi_{NN} - \Psi_{\text{actual}})g'(x_1, x_2)f_2(x_2)$$

Note that $g'(x) = g(x)(1-g(x))$, we then get

$$w_1^{t + 1} = w_1^t - \gamma(\Psi_{NN} - \Psi_{\text{actual}})g(\cdot)(1 - g(\cdot))f_1(x_1)$$
$$w_2^{t + 1} = w_2^t - \gamma(\Psi_{NN} - \Psi_{\text{actual}})g(\cdot)(1 - g(\cdot))f_2(x_2)$$

where $\gamma$ is called the learning rate. And that's it! Time to code.


---

**Activity**

Tweak the `gamma` and `y` variables and show us your highest attainable accuracy for each $\Psi$ column. What did you observe?


|$x_1$ | $x_2$ | $\Psi_{\text{AND}}$| $\Psi_{\text{OR}}$| $\Psi_{\text{XOR}}$|
| ---  | ----  |  -----| --- | --- |
| -1   | -1    | 0| 0 | 0|
|-1    | 1     | 0| 1| 1|
|1     | -1    | 0| 1| 1|
|1     | 1     |1 | 1| 0 |

**For simplicity, assume that $f(x) = x$. Therefore $f'(x) = 1$.**

In [4]:
# Define the activation function
def activation_function(x, deriv=False):
    sigmoid =  1 / (1 + np.exp(-x))
    if deriv:
        return sigmoid * (1 - sigmoid)
    return sigmoid

In [5]:
# Define our constants
gamma = 0.005
n_input_nodes = 2
n_output_nodes = 1


# Define inputs
# each row is a sample and col a feature
X = np.array(
    [
        [-1, -1],
        [-1, 1],
        [1, -1],
        [1, 1]
    ]
)

# Change the targets based on the chosen Psi column
y = np.array([[0, 1, 1, 0]]).T

# initialize weights
# have the initial weights have mean 0 and std = 1
# this is 2 by 1
w0 = np.random.normal(loc=0, scale=1, size=(n_input_nodes, n_output_nodes)) 
n_iters = int(1e4)

print(f"Initial weights:\n{w0}")
print("=" * 50)

# train the network
for i in range(n_iters):
    layer0 = X
    layer1 = activation_function(np.dot(layer0, w0))

    error = layer1 - y
    if i % 1000 == 0:
        print(f"Iter: {i} --- Error: {np.mean(np.abs(error)):.4f}")
    
    layer1_delta = error * activation_function(np.dot(layer0, w0), deriv=True)
    w0 -= gamma * np.dot(layer0.T, layer1_delta)


y_preds = np.rint(layer1).flatten()

print("=" * 50)
print("Raw Output after training:\n")
print(layer1)
print("Learned weights:\n")
print(w0)
print("-" * 50)
print(f"Thresholded result at 0.5:{y_preds}")
print(f"Accuracy: {accuracy_score(y, y_preds) * 100:.2f}%")

Initial weights:
[[1.18999965]
 [1.08374483]]
Iter: 0 --- Error: 0.5000
Iter: 1000 --- Error: 0.5000
Iter: 2000 --- Error: 0.5000
Iter: 3000 --- Error: 0.5000
Iter: 4000 --- Error: 0.5000
Iter: 5000 --- Error: 0.5000
Iter: 6000 --- Error: 0.5000
Iter: 7000 --- Error: 0.5000
Iter: 8000 --- Error: 0.5000
Iter: 9000 --- Error: 0.5000
Raw Output after training:

[[0.49999311]
 [0.4999999 ]
 [0.5000001 ]
 [0.50000689]]
Learned weights:

[[1.39567020e-05]
 [1.35630693e-05]]
--------------------------------------------------
Thresholded result at 0.5:[0. 0. 1. 1.]
Accuracy: 50.00%


---

**Question:** If you were to change this to gradient ascent, what are the two major changes you would do?<br>
**Question:** What's a good reason why we're not getting accurate results?

---

### The Bias Node


**Activity: Adding a constant bias**

Tweak the `gamma` and `y` variables and show us your highest attainable accuracy for each $\Psi$ column. What did you observe?


|$x_1$ | $x_2$ | $\Psi_{\text{AND}}$| $\Psi_{\text{OR}}$| $\Psi_{\text{XOR}}$|
| ---  | ----  |  -----| --- | --- |
| -1   | -1    | 0| 0 | 0|
|-1    | 1     | 0| 1| 1|
|1     | -1    | 0| 1| 1|
|1     | 1     |1 | 1| 0 |

Below is the architecture of this network for your reference

<figure align="center">
<img src="figures/basic-bias-network.png" width="50%">
</figure>

**For simplicity, assume that $f(x) = x$. Therefore $f'(x) = 1$.**

In [6]:
# Define the activation function
def activation_function(x, deriv=False):
    sigmoid =  1 / (1 + np.exp(-x))
    if deriv:
        return sigmoid * (1 - sigmoid)
    return sigmoid

In [7]:
# Define our constants
gamma = 0.005
n_input_nodes = 3 # notice that we changed this
n_output_nodes = 1


# Define inputs

X = np.array(
    [
        [-1, -1],
        [-1, 1],
        [1, -1],
        [1, 1]
    ]
)
bias = [1, 1, 1, 1] # These are not learnable in this case
X = np.insert(X, 0, bias, axis=1)

# Change the targets based on the chosen Psi column
y = np.array([[0, 1, 1, 0]]).T

# initialize weights
# have the initial weights have mean 0 and std = 1
w1 = np.random.normal(loc=0, scale=1, size=(n_input_nodes, n_output_nodes)) 
n_iters = int(1e4)

print(f"Initial weights:\n{w1}")
print("=" * 50)

# train the network
for i in range(n_iters):
    layer0 = X
    layer1 = activation_function(np.dot(layer0, w1))

    error = layer1 - y
    if i % 1000 == 0:
        print(f"Iter {i} --- Error: {np.mean(np.abs(error)):.4f}")
    
    layer1_delta = error * activation_function(np.dot(layer0, w1), deriv=True)
    w1 -= gamma * np.dot(layer0.T, layer1_delta)

y_preds = [1 if x > 0.5 else 0 for x in layer1]

print("=" * 50)
print("Raw Output after training:\n")
print(layer1)
print("Learned weights:\n")
print(w1)
print("-" * 50)
print(f"Thresholded result at 0.5:{y_preds}")
print(f"Accuracy: {accuracy_score(y, y_preds) * 100:.2f}%")

Initial weights:
[[-0.60880486]
 [ 1.18697855]
 [ 0.45536896]]
Iter 0 --- Error: 0.5237
Iter 1000 --- Error: 0.5006
Iter 2000 --- Error: 0.5000
Iter 3000 --- Error: 0.5000
Iter 4000 --- Error: 0.5000
Iter 5000 --- Error: 0.5000
Iter 6000 --- Error: 0.5000
Iter 7000 --- Error: 0.5000
Iter 8000 --- Error: 0.5000
Iter 9000 --- Error: 0.5000
Raw Output after training:

[[0.49999769]
 [0.49999722]
 [0.50000102]
 [0.50000055]]
Learned weights:

[[-3.52607873e-06]
 [ 6.64825566e-06]
 [-9.33467778e-07]]
--------------------------------------------------
Thresholded result at 0.5:[0, 0, 1, 1]
Accuracy: 50.00%


---

**Activity: Hidden Layers**

Provide the forward- and back- propagation of the network shown below.

Tweak the `gamma1`, `gamma2`, and `y` variables and show us your highest attainable accuracy for each $\Psi$ column. What did you observe?


|$x_1$ | $x_2$ | $\Psi_{\text{AND}}$| $\Psi_{\text{OR}}$| $\Psi_{\text{XOR}}$|
| ---  | ----  |  -----| --- | --- |
| -1   | -1    | 0| 0 | 0|
|-1    | 1     | 0| 1| 1|
|1     | -1    | 0| 1| 1|
|1     | 1     |1 | 1| 0 |

Below is the architecture for this network. Note that the bias nodes are present in the input and hidden layers and have been excluded from the diagram. It's an issue with the image itself.

<figure align="center">
<img src="figures/with-hidden.png" width="80%">
</figure>

**For simplicity, assume that $f(x) = x$. Therefore $f'(x) = 1$.**

In [8]:
# Define the activation function
def activation_function(x, deriv=False):
    sigmoid =  1 / (1 + np.exp(-x))
    if deriv:
        return sigmoid * (1 - sigmoid)
    return sigmoid


In [9]:
# Define our constants

# gamma = learning rate
gamma1 = 0.01
gamma2 = 0.01

n_input_nodes = 2
n_hidden_nodes = 2
n_output_nodes = 1

# Define inputs

X = np.array(
    [
        [-1, -1],
        [-1, 1],
        [1, -1],
        [1, 1]
    ]
)
# bias = [1, 1, 1, 1] # These are not learnable in this case
# X = np.insert(X, 0, bias, axis=1)
X = np.hstack([X, np.ones((X.shape[0], 1))])  # Add bias column


y = np.array([[0, 1, 1, 1]]).T

# initialize weights
# have the initial weights have mean 0 and std = 1
w1 = 2 * np.random.random((n_input_nodes + 1, n_hidden_nodes)) - 1  
w2 = 2 * np.random.random((n_hidden_nodes + 1, n_output_nodes)) - 1 
n_iters = int(1e4)

print(f"Initial weights:\n")
print(f"{w1=}\n")
print(f"{w2=}\n")
print("=" * 50)

# train the network
for i in range(n_iters):
    layer0 = X

    layer1_input = np.dot(layer0, w1)
    layer1 = activation_function(layer1_input)
    layer1_b = np.hstack([layer1, np.ones((layer1.shape[0], 1))])  

    layer2_input = np.dot(layer1_b, w2)
    layer2 = activation_function(layer2_input)

    error = layer2 - y
    if i % 1000 == 0:
        print(f"Iter {i} --- Error: {np.mean(np.abs(error)):.2f}")
    
    layer2_delta = error * activation_function(layer2_input, deriv=True)
    layer1_delta = layer2_delta.dot(w2.T) * activation_function(layer1_b, deriv=True)
    layer1_delta = layer1_delta[:, :-1]

    w2 -= gamma2 * layer1_b.T.dot(layer2_delta)
    w1 -= gamma1 * layer0.T.dot(layer1_delta)


    
y_preds = np.rint(layer2).flatten()
print("=" * 50)
print("Raw Output after training:\n")
print(layer2)
print("Learned weights:\n")
print(f"{w1=}\n")
print(f"{w2=}\n")
print("-" * 50)
print(f"Thresholded result at 0.5:{y_preds}")
print(f"Accuracy: {accuracy_score(y, y_preds) * 100:.2f}%")

Initial weights:

w1=array([[ 0.84807565,  0.95088395],
       [-0.04371296,  0.83862796],
       [-0.65294523,  0.46088019]])

w2=array([[0.08705342],
       [0.14168158],
       [0.06164246]])

Iter 0 --- Error: 0.47
Iter 1000 --- Error: 0.32
Iter 2000 --- Error: 0.28
Iter 3000 --- Error: 0.24
Iter 4000 --- Error: 0.22
Iter 5000 --- Error: 0.20
Iter 6000 --- Error: 0.19
Iter 7000 --- Error: 0.19
Iter 8000 --- Error: 0.18
Iter 9000 --- Error: 0.17
Raw Output after training:

[[0.29627379]
 [0.8090573 ]
 [0.81100287]
 [0.99726094]]
Learned weights:

w1=array([[ 3.69423415,  6.66179867],
       [ 3.13306324,  6.907899  ],
       [-1.05193575, -0.49533201]])

w2=array([[ 2.41280641],
       [ 4.35847479],
       [-0.86605537]])

--------------------------------------------------
Thresholded result at 0.5:[0. 1. 1. 1.]
Accuracy: 100.00%


### How do we make predictions on our trained network?

So far we've discussed about training a neural network, but we haven't gotten to the point of actually making predictions (inferences) on new data. To make our discussion simpler, let's just use the same inputs. 

We've seen that in the process of training, we're conducting backpropagation. However for inference tasks, we only need to do the forward propagation. We simply take our trained weights and pass them to our inputs. We'll implement the `forward` and `predict` functions for the forward propagation and inference, respectively.

In [10]:
# Define the activation function
def activation_function(x, deriv=False):
    sigmoid =  1 / (1 + np.exp(-x))
    if deriv:
        return sigmoid * (1 - sigmoid)
    return sigmoid


In [11]:
def forward(X, w1, w2):

    # add a constant bias column
    X_with_bias = np.hstack([X, np.ones((X.shape[0], 1))])

    # alternatively, you can use the @ operator 
    # for more convenience
    # Ex: input_to_hidden = X_with_bias @ w1
    input_to_hidden = np.dot(
        X_with_bias, w1
    )
    
    hidden = activation_function(input_to_hidden)
    hidden_with_bias = np.hstack(
        [hidden, np.ones((hidden.shape[0], 1))]
    )
    hidden_to_out = np.dot(hidden_with_bias, w2)
    return activation_function(hidden_to_out)

def predict(X, w1, w2, thresh=0.5):
    output_prob = forward(X, w1, w2)
    return np.rint(layer2).flatten()

In [14]:
# Example

X = np.array(
    [
        [1, -1],
        [-1, 1],
        [1, -1],
        [1, 1]
    ]
)

y_true = np.array([[1, 1, 1, 1]]).T

preds = predict(X, w1, w2)
print(f"Accuracy: {accuracy_score(y_true, y_preds) * 100:.2f}%")

Accuracy: 75.00%
